version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
      - TZ=Europe/Bratislava
    expose:
      - "3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "/api"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Bratislava
    depends_on:
      - backend
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/nginx/www:/var/www/certbot
    depends_on:
      - frontend
      - backend