version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000